#+TITLE: WKF - Doom Emacs - Config

Place your private configuration here! Remember, you do not need to run =doom sync= after modifying this file!

* User Data

Some functionality uses this to identify you, e.g.GPG configuration, email clients, file templates and snippets.

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Wahidyan Kresna Fridayoka" user-mail-address "wahidyankf@gmail.com")
#+END_SRC

* Theme
** StartUp

#+BEGIN_SRC emacs-lisp
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
#+END_SRC

** Template

There are two ways to load a theme.Both assume the theme is installed and available.You can either set =doom-theme= or manually load a theme with the =load-theme= function. This is the default:

#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-one)
#+END_SRC

This determines the style of line numbers in effect. If set to =nil=, line numbers are disabled. For relative line numbers, set this to =relative=.

** Font

Doom exposes five(optional) variables for controlling fonts in Doom.Here
are the three important ones:

- =doom-font=
- =doom-variable-pitch-font=
- =doom-big-font=
  - used for =doom-big-font-mode=
  - use this for presentations or streaming.

They all accept either a =font-spec=, =font string("Input Mono-12")=, or =xlfd= font string. You generally only need these two:

#+BEGIN_EXAMPLE emacs-lisp
(setq doom-font
  (font-spec :family "monospace" :size 12 :weight 'semi-light)
  doom-variable-pitch-font (font-spec :family "sans" :size 13))
#+End_example

#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "Dank Mono" :size 12))
#+END_SRC

** Editor

#+BEGIN_SRC emacs-lisp
(blink-cursor-mode t)
(setq display-line-numbers-type 'relative)
(setq-default indicate-empty-lines t)
(setq-default show-trailing-whitespace t)
#+END_SRC

** Doom Message

Here are some additional functions / macros that could help you configure Doom:
- =load!= for loading external *.el files relative to this one
- =use-package= for configuring packages
  - =after!= for running code after a package has loaded
- =add-load-path!= for adding directories to the =load-path=, relative to this file.Emacs searches the=load-path= when you load packages with =require= or =use-package=.
- =map!= for binding new keys

*** Doom Modeline

#+BEGIN_SRC emacs-lisp
(display-time-mode)
(display-battery-mode)
#+END_SRC

* Frame

#+BEGIN_SRC emacs-lisp
;; Frame Make
(define-key evil-normal-state-map (kbd "<backspace> f m") 'make-frame-command)
;; Frame Z (cycle)
(define-key evil-normal-state-map (kbd "<backspace> f z") 'other-frame)
;; Frame Delete Delete (current)
(define-key evil-normal-state-map (kbd "<backspace> f d d") 'delete-frame)
;; Frame Delete Other
(define-key evil-normal-state-map (kbd "<backspace> f d o") 'delete-other-frames)
#+END_SRC

* Window

#+BEGIN_SRC emacs-lisp
(defun wkf/evil-window-vsplit ()
  "VSplit then focus on the right pane"
  (interactive)
  (evil-window-vsplit)
  (evil-window-right 1))

(defun wkf/evil-window-split ()
  "Split then focus on the bottom pane"
  (interactive)
  (evil-window-split)
  (evil-window-down 1))

;; | (vertical)
(define-key evil-normal-state-map (kbd "<backspace> \\ ") 'wkf/evil-window-vsplit)
;; - (horizontal)
(define-key evil-normal-state-map (kbd "<backspace> - ") 'wkf/evil-window-split)
;; = (equal)
(define-key evil-normal-state-map (kbd "<backspace> = ") 'balance-windows)
#+END_SRC

* Terminal

#+BEGIN_SRC emacs-lisp
;; terminal (mini)
(define-key evil-normal-state-map (kbd "<backspace> t") '+vterm/toggle)
;; Terminal (max)
(define-key evil-normal-state-map (kbd "<backspace> T") '+vterm/here)
#+END_SRC

** File

#+BEGIN_SRC emacs-lisp
(defun wkf/windows-rebalance ()
  "Balance window then recenter"
  (interactive)
  (balance-windows)
  (recenter))

(defun wkf/find-file (filename)
  "Search filename and open it in the right vertical split"
  (interactive)
  (wkf/evil-window-vsplit)
  (find-file filename)
  (wkf/windows-rebalance))

(defun wkf/find-zshrc ()
  "Open my zshrc in the right vertical split"
  (interactive)
  (wkf/find-file "~/.zshrc"))

(defun wkf/find-emacs-init ()
  "Open my init.el in the right vertical split"
  (interactive)
  (wkf/find-file "~/.doom.d/init.el"))

(defun wkf/find-emacs-packages ()
  "Open my packages.el in the right vertical split"
  (interactive)
  (wkf/find-file "~/.doom.d/packages.el"))

(defun wkf/find-emacs-config-org ()
  "Open my config.org in the right vertical split"
  (interactive)
  (wkf/find-file "~/.doom.d/config.org"))

(defun wkf/find-emacs-config-el ()
  "Open my config.org in the right vertical split"
  (interactive)
  (wkf/find-file "~/.doom.d/config.el"))

(defun wkf/find-emacs-scratch ()
  "Open my scratch.el in the right vertical split"
  (interactive)
  (wkf/find-file "~/.doom.d/scratch.el"))

;; Config ZSH
(define-key evil-normal-state-map (kbd "<backspace> c z") 'wkf/find-zshrc)
;; Config Emacs Init.el
(define-key evil-normal-state-map (kbd "<backspace> c e i") 'wkf/find-emacs-init)
;; Config Emacs Packages.el
(define-key evil-normal-state-map (kbd "<backspace> c e p") 'wkf/find-emacs-packages)
;; Config Emacs Config.org
(define-key evil-normal-state-map (kbd "<backspace> c e c") 'wkf/find-emacs-config-org)
;; Config Emacs Config.el (compiled version)
(define-key evil-normal-state-map (kbd "<backspace> c e C") 'wkf/find-emacs-config-el)
;; Config Emacs Scratch.el
(define-key evil-normal-state-map (kbd "<backspace> c e s") 'wkf/find-emacs-scratch)
#+END_SRC

** Editing

#+BEGIN_SRC emacs-lisp
(defun wkf/save-buffer ()
  "Save current buffer with custom lsp formatting"
  (interactive)
  (if (and (equal major-mode 'lsp-mode)
           (not (equal major-mode 'reason-mode)))
      (progn (lsp-format-buffer)
             (save-buffer))
    (if (equal major-mode 'emacs-lisp-mode)
        (progn (elisp-format-buffer)
               (save-buffer))
      (save-buffer))))

;; Write
(define-key evil-normal-state-map (kbd ", w") 'wkf/save-buffer)
;; Quit
(define-key evil-normal-state-map (kbd ", q") 'delete-window)
#+END_SRC

* Git

#+BEGIN_SRC emacs-lisp
;; Git Wkf Update All
(define-key evil-normal-state-map (kbd "<backspace> g w u a")
  (kbd "SPC o t git_wkf_update_all <return>"))
#+END_SRC

* Plugin - Wakatime

#+BEGIN_SRC emacs-lisp
(use-package! wakatime-mode
  :hook (after-init . global-wakatime-mode))
#+END_SRC

* Plugin - LSP Mode
** COMMENT LSP Mode

#+BEGIN_SRC emacs-lisp
(use-package! lsp-mode
  :hook (reason-mode . lsp)
  :hook (haskell-mode . lsp)
  :hook (tuareg-mode . lsp)
  :config (lsp-register-client (make-lsp-client :new-connection (lsp-stdio-connection "ocamllsp")
                                                :major-modes '(tuareg-mode)
                                                :notification-handlers (ht ("client/registerCapability"
                                                                            'ignore))
                                                :priority 1
                                                :server-id 'ocaml-ls))
  :config (lsp-register-client (make-lsp-client :new-connection (lsp-stdio-connection
                                                                 "~/.doom.d/rls-macos/reason-language-server")
                                                :major-modes '(reason-mode)
                                                :notification-handlers (ht ("client/registerCapability"
                                                                            'ignore))
                                                :priority 1
                                                :server-id 'reason-ls))
  :config (setq lsp-lens-auto-enable t)
  :commands (lsp-mode lsp-define-stdio-client))
#+END_SRC

** LSP UI

#+BEGIN_SRC emacs-lisp
(use-package! lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :config (set-lookup-handlers! 'lsp-ui-mode
            :definition #'lsp-ui-peek-find-definitions
            :references #'lsp-ui-peek-find-references)
  (setq lsp-ui-doc-max-height 16 lsp-ui-doc-max-width 50 lsp-ui-sideline-ignore-duplicate t))
#+END_SRC

** Company LSP

#+BEGIN_SRC emacs-lisp
(use-package! company-lsp
  :after lsp-mode
  :config (set-company-backend! 'lsp-mode 'company-lsp)
  (setq company-lsp-enable-recompletion t))
#+END_SRC

** Intellisense

To get information about any of these functions/macros, move the cursor over the highlighted symbol at press =K= (non-evil users must press =C-c g k=). This will open documentation for it, including demos of how they are used.

#+BEGIN_SRC emacs-lisp
(defun wkf/gdef ()
  "Open +lookup/definition in the split window below"
  (interactive)
  (+lookup/definition (doom-thing-at-point-or-region))
  (evil-window-split)
  (evil-jump-backward-swap)
  (evil-window-down 1)
  (balance-windows)
  (recenter))

(defun wkf/gdoc ()
  "Open +lookup/documentation in the mini buffer"
  (interactive)
  (+lookup/documentation (doom-thing-at-point-or-region))
  (evil-window-down 1)
  (balance-windows)
  (recenter))

;; doKumentation
(define-key evil-normal-state-map (kbd "K") 'lsp-ui-doc-glance)
;; Go to Definition
(define-key evil-normal-state-map (kbd ", g d") 'wkf/gdef)
;; Go to doKumentation
(define-key evil-normal-state-map (kbd ", g k") 'wkf/gdoc)
;; compile
(define-key evil-normal-state-map (kbd ", C") 'compile)
;; recompile
(define-key evil-normal-state-map (kbd ", c") 'recompile)
#+END_SRC

** Haskell

#+BEGIN_SRC emacs-lisp
(use-package! lsp-haskell
  :after lsp-mode
  :config (setq lsp-haskell-process-path-hie "hie-wrapper")
  (lsp-haskell-set-formatter-floskell))
#+END_SRC

** ReasonML

#+BEGIN_SRC emacs-lisp
(use-package! reason-mode
  :mode "\\.re$"
  :hook (before-save . (lambda ()
                         (when (equal major-mode 'reason-mode)
                           (refmt)))))
#+END_SRC

** Emacs Lisp

#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-lisp-mode-hook 'turn-on-eldoc-mode)
#+END_SRC

** DAP Mode

#+BEGIN_SRC emacs-lisp
(use-package! dap-mode
  :after lsp-mode
  :config (dap-mode t)
  (dap-ui-mode t))
#+END_SRC

** TypeScript

#+BEGIN_SRC emacs-lisp
(use-package! lsp-typescript
  :when (featurep! +javascript)
  :hook ((js2-mode typescript-mode) . lsp-typescript-enable))
#+END_SRC

** CSS

#+BEGIN_SRC emacs-lisp
(use-package! lsp-css
  :when (featurep! +css)
  :hook ((css-mode less-mode scss-mode) . lsp-css-enable))
#+END_SRC

** Sh

#+BEGIN_SRC emacs-lisp
(when (featurep! +sh)
  (after! sh-script (lsp-define-stdio-client lsp-sh #'projectile-project-root '("bash-language-server"
                                                                                "start"))
    (add-hook 'sh-mode-hook #'lsp-sh-enable)))
#+END_SRC

* Plugin - Org Mode
** Directory

If you use =org= and don't want your org files in the default location below, change =org-directory=. It must be set before org loads!

#+BEGIN_SRC emacs-lisp
(setq org-directory "~/wkf-org/")
#+END_SRC

** Editing

#+BEGIN_SRC emacs-lisp
;; Org SRC Edit
(evil-define-key 'normal org-mode-map (kbd "<backspace> o s '") 'org-edit-special)

;; Org SRC Format
(evil-define-key 'normal org-mode-map (kbd "<backspace> o s f")
  (kbd "<backspace> o s ' , w : q"))
#+END_SRC

** Images

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'org-display-user-inline-images)
(add-hook 'org-mode-hook 'org-display-inline-images)
(add-hook 'org-mode-hook 'org-redisplay-inline-images)

;; Org Images toggle(z)
(evil-define-key 'normal org-mode-map (kbd "<backspace> o i z") 'org-toggle-inline-images)
;; Org Images yes
(evil-define-key 'normal org-mode-map (kbd "<backspace> o i y") 'org-display-inline-images)
;; Org Images no
(evil-define-key 'normal org-mode-map (kbd "<backspace> o i n") 'org-remove-inline-images)
#+END_SRC

** Open at Point

#+BEGIN_SRC emacs-lisp
(defun wkf/org-open-at-point ()
  "Put org-mode's open at point's content to the right vertical split"
  (interactive)
  (evil-window-vsplit)
  (evil-window-right 1)
  (org-open-at-point)
  (balance-windows))

;; Org Open
(evil-define-key 'normal org-mode-map (kbd "<backspace> o o") 'wkf/org-open-at-point)
#+END_SRC

** Org Tree Slide

#+BEGIN_SRC emacs-lisp
;; Org Presentation
(evil-define-key 'normal org-mode-map (kbd "<backspace> o p") 'org-tree-slide-mode)
;; >
(evil-define-key 'normal org-mode-map (kbd "s-.") 'org-tree-slide-move-next-tree)
;; <
(evil-define-key 'normal org-mode-map (kbd "s-,") 'org-tree-slide-move-previous-tree)
#+END_SRC

* Plugin - DeadGrep

#+BEGIN_SRC emacs-lisp
(define-key evil-normal-state-map (kbd ", d g g") 'deadgrep)
(define-key evil-normal-state-map (kbd ", d g r") 'deadgrep-restart)
#+END_SRC
