ln -s ~/Dropbox/wkf-devbox/ack/.ackrc ~/.ackrc
ln -s ~/Dropbox/wkf-devbox/doom-emacs/.doom.d ~/.doom.d
ln -s ~/Dropbox/wkf-devbox/ocaml/.ocamlinit ~/.ocamlinit
ln -s ~/Dropbox/wkf-devbox/ssh/abdurrahman/.ssh ~/.ssh
ln -s ~/Dropbox/wkf-devbox/tmux/.tmux ~/.tmux
ln -s ~/Dropbox/wkf-devbox/tmux/.tmux.conf ~/.tmux.conf
ln -s ~/Dropbox/wkf-devbox/vim/.vim ~/.vim
ln -s ~/Dropbox/wkf-devbox/vim/.vimrc ~/.vimrc
ln -s ~/Dropbox/wkf-devbox/zsh/.zshrc ~/.zshrc
ln -s ~/Dropbox/wkf-book ~/wkf-book
ln -s ~/Dropbox/wkf-devbox ~/wkf-devbox
ln -s ~/Dropbox/wkf-learn ~/wkf-learn
ln -s ~/Dropbox/wkf-notes ~/wkf-notes
ln -s ~/Dropbox/wkf-org ~/wkf-org
